### ISSUE TITLE
Native assets not build on Windows anymore

### ISSUE THREAD

**Issue by paulrutter** [blueconic/node-oom-heapdump#22]
I updated some dependencies and added a few Node versions (and removed some older ones).
@spmiller can you check why this action doesn't succeed anymore?

https://github.com/blueconic/node-oom-heapdump/actions/runs/1822665059

Thanks in advance.

**Comment by paulrutter** [comment]
Great! Thanks for the swift response @spmiller 
I made some changes on master, but that didn't solve it yet.

**Comment by spmiller** [comment]
Hello again @paulrutter, I submitted a PR to fix the Windows issue. I got green builds with it on [my fork](https://github.com/spmiller/node-oom-heapdump/releases/tag/v2%2C1).

I didn't look into the 'upload an artifact that is already there' error message -- do you want me to investigate further here or are you OK just deleting the artifacts and re-triggering the build?

**Comment by paulrutter** [comment]
Yes, i think that's fine.
I'll check later today, thanks!
