### ISSUE TITLE
[Intermittent] : segmentation faults with nodejsv14.18.3 on ubuntu/centos

### ISSUE THREAD

**Issue by ChandrasekharPo-Kore** [blueconic/node-oom-heapdump#25]
We are seeing segmentation fault errors with nodejs v14.18.3. Its intermittent

Test : npm run test from the module
OS : Linux 5.14.0-1054-oem #61-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

NOTE : No issues seen with nodejs v16.x.x

handrasekharposhamolla@KI0535:~/workspace/research/node_modules/node-oom-heapdump$ npm run test

> node-oom-heapdump@3.0.1 test workspace/research/node_modules/node-oom-heapdump
> node --max_old_space_size=80 --inspect ./tests/oom_app.js

Debugger listening on ws://127.0.0.1:9229/5dc48fd2-806d-4383-9f71-73bdaa030127
For help, see: https://nodejs.org/en/docs/inspector
Debugger is listening on port 9229, 'node-oom-heapdump' can function correctly.
Leaks: 100000
Leaks: 200000
Leaks: 300000
Leaks: 400000
Leaks: 500000
Leaks: 600000
Leaks: 700000
Leaks: 800000
Leaks: 900000
Leaks: 1000000
Leaks: 1100000
Leaks: 1200000
Leaks: 1300000
Leaks: 1400000
Leaks: 1500000
Leaks: 1600000
Leaks: 1700000
Leaks: 1800000
Leaks: 1900000
Leaks: 2000000
Leaks: 2100000
Leaks: 2200000
Leaks: 2300000
Leaks: 2400000

<--- Last few GCs --->

[531231:0x54f6830]     2892 ms: Mark-sweep (reduce) 80.1 (83.2) -> 80.0 (85.0) MB, 121.2 / 0.0 ms  (+ 0.0 ms in 13 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 122 ms) (average mu = 0.250, current mu = 0.032) allocati[531231:0x54f6830]     3052 ms: Mark-sweep (reduce) 81.0 (85.0) -> 81.0 (86.0) MB, 158.5 / 0.0 ms  (+ 0.0 ms in 10 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 159 ms) (average mu = 0.127, current mu = 0.008) allocati

<--- JS stacktrace --->

Generating Heapdump to 'workspace/research/node_modules/node-oom-heapdump/tests/my_heapdump.heapsnapshot' now...
Segmentation fault
------------------------------------------------------------------------------------------------------------------------
::: Segmentation trace :::

.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal4Heap25GarbageCollectionPrologueEv+0x184)[0xd7ab34]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal4Heap14CollectGarbageENS0_15AllocationSpaceENS0_23GarbageCollectionReasonENS_15GCCallbackFlagsE+0x17e)[0xd828ee]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal4Heap24PreciseCollectAllGarbageEiNS0_23GarbageCollectionReasonENS_15GCCallbackFlagsE+0x40)[0xd84460]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal21HeapSnapshotGenerator16GenerateSnapshotEv+0x35)[0x1021e15]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal12HeapProfiler12TakeSnapshotEPNS_15ActivityControlEPNS_12HeapProfiler18ObjectNameResolverEb+0x74)[0x1012174]
workspace/research/node_modules/node-oom-heapdump/build/Release/node_oom_heapdump_native.node(+0x27e1)[0x7f19acf1a7e1]
workspace/research/node_modules/node-oom-heapdump/build/Release/node_oom_heapdump_native.node(_Z10OnOOMErrorPKcb+0x19)[0x7f19acf1a8e9]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v85Utils16ReportOOMFailureEPNS_8internal7IsolateEPKcb+0x20)[0xbb7e90]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal2V823FatalProcessOutOfMemoryEPNS0_7IsolateEPKcb+0x347)[0xbb8237]
.nvm/versions/node/v14.18.3/bin/node[0xd74445]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal23EvacuateNewSpaceVisitor5VisitENS0_10HeapObjectEi+0x24e)[0xda4dde]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal13FullEvacuator15RawEvacuatePageEPNS0_11MemoryChunkEPl+0xe56)[0xdb0e16]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal9Evacuator12EvacuatePageEPNS0_11MemoryChunkE+0x7f)[0xd9cfaf]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal18PageEvacuationTask13RunInParallelENS0_15ItemParallelJob4Task6RunnerE+0xa8)[0xd9d228]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal15ItemParallelJob3RunEv+0x1f9)[0xd8fb09]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal24MarkCompactCollectorBase31CreateAndExecuteEvacuationTasksINS0_13FullEvacuatorENS0_20MarkCompactCollectorEEEvPT0_PNS0_15ItemParallelJobEPNS0_17MigrationObserverEl+0x590)[0xdb2d70]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal20MarkCompactCollector23EvacuatePagesInParallelEv+0x2ac)[0xdb360c]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal20MarkCompactCollector8EvacuateEv+0x125)[0xdb37d5]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal20MarkCompactCollector14CollectGarbageEv+0xf1)[0xdc57d1]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal4Heap11MarkCompactEv+0xd8)[0xd81a98]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal4Heap14CollectGarbageENS0_15AllocationSpaceENS0_23GarbageCollectionReasonENS_15GCCallbackFlagsE+0xe18)[0xd83588]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal4Heap34AllocateRawWithRetryOrFailSlowPathEiNS0_14AllocationTypeENS0_16AllocationOriginENS0_19AllocationAlignmentE+0x5c)[0xd869cc]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal7Factory11AllocateRawEiNS0_14AllocationTypeENS0_19AllocationAlignmentE+0x9d)[0xd4c19d]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal11FactoryBaseINS0_7FactoryEE26AllocateRawWithImmortalMapEiNS0_14AllocationTypeENS0_3MapENS0_19AllocationAlignmentE+0x14)[0xd46024]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal11FactoryBaseINS0_7FactoryEE19NewRawOneByteStringEiNS0_14AllocationTypeE+0x50)[0xd48030]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal7Factory11SmiToStringENS0_3SmiENS0_15NumberCacheModeE+0x88)[0xd5c108]
.nvm/versions/node/v14.18.3/bin/node(_ZN2v88internal26Runtime_NumberToStringSlowEiPmPNS0_7IsolateE+0x45)[0x10a8f95]
.nvm/versions/node/v14.18.3/bin/node[0x14467f9]
Segmentation fault

**Comment by paulrutter** [comment]
In node 14 there is now native support for heapdumps, can you try this instead? https://github.com/blueconic/node-oom-heapdump#nodejs-1418x

**Comment by paulrutter** [comment]
stale
