### ISSUE TITLE
What would be the changes need if this module used in node v6.11 ?

### ISSUE THREAD

**Issue by sahanmal** [blueconic/node-oom-heapdump#5]
Hi 

We are using node v6.11 at our production. We need to take heapdump when node out of memory happened. What are the changes needed if we want to use this module in our production env ?

**Comment by paulrutter** [comment]
Hi @sahanmal,

Apart from the fact that Node.js 6 is going out of maintenance mode [april next year](https://github.com/nodejs/Release#release-schedule), the changes needed for node-oom-heapdump would probably be quite minor.

I haven't specifically tested it, but changes are to be expected in:

- https://github.com/blueconic/node-oom-heapdump/blob/master/lib/node_oom_heapdump_native.cc#L59
  
When looking at v8-profiler (which supports multiple versions), it looks like the code this module currently uses should work for Node.js 6.11 as well (see https://github.com/node-inspector/v8-profiler/blob/master/src/heap_profiler.cc#L75).

Have you tested in Node.js 6.11? What didn't work or what is the error you got?

**Comment by paulrutter** [comment]
Closing issue as there is no response.
